### Replace 'placeholder' with an existing GUID
# Open GETALL.rest file to request list of items
@id = placeholder

### Base URL
@host = http://localhost:5000

### Documented Responses
# 500 Internal Server Error
# 404 Not Found
# 200 OK
GET {{host}}/api/item/{{id}}
