### Base URL
@host = http://localhost:5000

### Documented Response
# 500 Internal Server Error
# 201 Created
POST {{host}}/api/item
Content-Type: application/json

{
    "name": "Assault Cuirass",
    "description": "An armor crafted from the scales of a Pure Silver Dragon."
}

### Documented Response
# 500 Internal Server Error
# 400 Bad Request
POST {{host}}/api/item
Content-Type: application/json

{
    "name": "",
    "description": ""
}
