// <auto-generated />
using System;
using Game.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game.Infrastructure.Migrations
{
    [DbContext(typeof(GameDBContext))]
    [Migration("20230502034032_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a489374e-48ea-47f2-8fff-860f142f27b8"),
                            Description = "A dagger crafted from the tooth of a Pure Silver Dragon.",
                            Name = "Dagon",
                            Timestamp = new DateTime(2023, 5, 2, 3, 40, 31, 722, DateTimeKind.Utc).AddTicks(8755)
                        },
                        new
                        {
                            Id = new Guid("519ed1bf-4664-4680-aed5-0dea811198a7"),
                            Description = "A sword crafted from the talon of a Pure Silver Dragon.",
                            Name = "Yasha",
                            Timestamp = new DateTime(2023, 5, 2, 3, 40, 31, 722, DateTimeKind.Utc).AddTicks(8826)
                        },
                        new
                        {
                            Id = new Guid("4fc17fe1-a8e1-43d8-a830-9229e8bb5e2a"),
                            Description = "A bow crafted from the wing of a Pure Silver Dragon.",
                            Name = "Buriza",
                            Timestamp = new DateTime(2023, 5, 2, 3, 40, 31, 722, DateTimeKind.Utc).AddTicks(8832)
                        },
                        new
                        {
                            Id = new Guid("ea86c683-d09a-4142-a822-a122543d7b76"),
                            Description = "A shield crafted from the scales of a Pure Silver Dragon.",
                            Name = "Vanguard",
                            Timestamp = new DateTime(2023, 5, 2, 3, 40, 31, 722, DateTimeKind.Utc).AddTicks(8836)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
